version: '2'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/ddata/portainer/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    ports:
      - 9000:9000
      #- 8000:8000 api ssh tun for remote portainer agent e.g. edge instance 
    restart: always